name: test-and-preview.yml

on:
  push:
    branches:
      - dev
      - staging
  workflow_dispatch:

jobs:
  test:
    name: "Test using Playwright"
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - uses: actions/setup-node@v2
        with:
          node-version: "17"

      - name: Install dependencies
        run: |
          npm install
          npx playwright install-deps
          npx playwright install

      - name: Run Playwright Tests
        continue-on-error: false
        run: |
          npx playwright test --reporter=html

  preview:
    name: Deploy to Cloudflare Pages (Preview)
    needs: [test]
    uses: ./.github/workflows/deploy-to-pages.yml
    secrets: inherit
